# Generated by Django 4.0.5 on 2022-06-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unify_phone_from_json', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phone',
            table='phone',
        ),
    ]
